services:
  server:
    container_name: continuum-server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    restart: unless-stopped
    ports:
      - 3003:3001
    env_file:
      - ./apps/server/.env
    volumes:
      - uploads_data:/app/uploads
    networks:
      - continuum-network

  web:
    container_name: continuum-web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - DOCKER_BUILD=true
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    restart: unless-stopped
    ports:
      - 3002:3000
    environment:
      - DOCKER_ENV=true
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    env_file:
      - ./apps/web/.env
    networks:
      - continuum-network
    depends_on:
      - server

volumes:
  uploads_data:

networks:
  continuum-network:
    driver: bridge
