services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: continuum-web
    ports:
      - '3000:3000'
    env_file:
      - apps/web/.env
      - .env
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    restart: on-failure:5
    networks:
      - app_network
    command: ['pnpm', '--filter', 'web', 'run', 'start']

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: continuum-server
    ports:
      - '3001:3001'
    env_file:
      - apps/server/.env
      - packages/db/.env
      - .env
    environment:
      - NODE_ENV=development
    restart: on-failure:5
    networks:
      - app_network
    volumes:
      - ./apps/server/uploads:/app/apps/server/uploads
    command: ['pnpm', '--filter', 'server', 'run', 'start']

networks:
  app_network:
    driver: bridge
