services:
  mongodb:
    image: mongo:7.0
    container_name: continuum-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: continuum
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - continuum-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-production
    container_name: continuum-server
    restart: unless-stopped
    ports:
      - '3001:3001'
    env_file:
      - ./apps/server/.env
      - ./packages/db/.env
    environment:
      # Override DATABASE_URL for Docker network
      - DATABASE_URL=mongodb://admin:password123@mongodb:27017/continuum?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongodb
    volumes:
      - uploads_data:/app/uploads
    networks:
      - continuum-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-production
    container_name: continuum-web
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - ./apps/web/.env
    environment:
      # Override API URL for Docker network
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=production
    depends_on:
      - server
    networks:
      - continuum-network

volumes:
  mongodb_data:
  uploads_data:

networks:
  continuum-network:
    driver: bridge
