import type { Metadata } from 'next';
import '@repo/ui/globals.css';
import { Montserrat } from 'next/font/google';
import Providers from '@/app/providers';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${montserrat.variable} font-montserrat`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
