export enum QuestionType {
  SHORT_ANSWER = 'SHORT_ANSWER',
  LONG_ANSWER = 'LONG_ANSWER',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  CHECKBOXES = 'CHECKBOXES',
  SCALE = 'SCALE',
  DROPDOWN = 'DROPDOWN',
  FILE_UPLOAD = 'FILE_UPLOAD',
  RATING = 'RATING',
  MULTIPLE_CHOICE_GRID = 'MULTIPLE_CHOICE_GRID',
  TICK_BOX_GRID = 'TICK_BOX_GRID',
}
